revamp infoembeds to have project-specific embeds
Faithful-Resource-Pack/Discord-Bot pull request #220
Opened 2023-01-03 20:04 UTC by 3vorp

should be self explanatory

2023-01-05 07:18 UTC, TheRolfFR approved these changes
I mean not much to say, maybe use a json file to store the embeds fields? What do you think @Juknum?

2023-01-05 07:18 UTC, TheRolfFR commented on commands/Compliance/infoembed.js
> +					.setThumbnail('https://raw.githubusercontent.com/faithful-resource-pack/branding/main/logos/transparent/512/f32_logo.png')
Should we use raw branding images from github  or from database @Juknum?

2023-01-05 07:22 UTC, 3vorp commented on commands/Compliance/infoembed.js
> +					.setThumbnail('https://raw.githubusercontent.com/faithful-resource-pack/branding/main/logos/transparent/512/f32_logo.png')
robert said that using the database is generally a bad idea as it's oftentimes outdated and more importantly it results in a lot of annoying api calls

also this command is probably gonna get replaced by a typescript version when the beta bot is finally actually merged into the old bot, and when that finally happens we can move the strings into the db

2023-01-05 07:25 UTC, 3vorp commented
oh also forgot to mention this in the initial description, but sorry for the janky indentation — the tabs are counted in the multi-line string which causes issues

discord handles tabs really weirdly and only renders them on some platforms (on my android phone it actually rendered for some reason), so I removed all of them just to be safe

2023-01-05 19:59 UTC, Juknum commented on commands/Compliance/infoembed.js
> +					.setThumbnail('https://raw.githubusercontent.com/faithful-resource-pack/branding/main/logos/transparent/512/f32_logo.png')
I recommend using the database, the database is now synced with the repo, and the database doesn't call the API, the API calls the database, so if you're calling the database directly you're fine, I think you have misunderstood what @RobertRR11 said about it, calling the database (or any subdomain) results in logs on Cloudflare but where I'm not sure about why Robert is complaining is because its flooding others logs? Which isn't a real issue since you can filter them and only display what you want to see? (let me know @RobertRR11 if I'm wrong)

2023-01-05 20:02 UTC, Juknum requested changes
Please switch GitHub raw URLs for the database, unless Robert has an explanation

2023-01-05 20:58 UTC, 3vorp commented on commands/Compliance/infoembed.js
> +					.setThumbnail('https://raw.githubusercontent.com/faithful-resource-pack/branding/main/logos/transparent/512/f32_logo.png')
eh sure I can just git revert it if robert doesn't like it

2023-01-06 00:56 UTC, Juknum approved these changes

2023-01-06 00:56 UTC, merged

2023-01-06 11:04 UTC, RobertRR11 commented on commands/Compliance/infoembed.js
> +					.setThumbnail('https://raw.githubusercontent.com/faithful-resource-pack/branding/main/logos/transparent/512/f32_logo.png')
> I recommend using the database, the database is now synced with the repo, and the database doesn't call the API, the API calls the database, so if you're calling the database directly you're fine, I think you have misunderstood what @RobertRR11 said about it, calling the database (or any subdomain) results in logs on Cloudflare but where I'm not sure about why Robert is complaining is because its flooding others logs? Which isn't a real issue since you can filter them and only display what you want to see? (let me know @RobertRR11 if I'm wrong)

The firewall has blocked 1,339,640 requests, guess how many of those are the database folder.