Fully replace legacy firestorm collections with modern API usage
Faithful-Resource-Pack/Discord-Bot pull request #250
Opened 2023-09-01 00:20 UTC by 3vorp

The current Firestorm collection system, while functional, isn't very intuitive and is largely made redundant by the API. Not only does this change finally modernize the entire codebase, but also means that new features can be added far more easily.

In addition, the API v2 structure is much more intuitive and easy to use than manually fetching from the database — the database internally still uses the API v1 scheme and is more likely to be subject to breaking changes in the future.

I also made a bunch of miscellaneous changes:
- Use the `module-aliases` npm module to simplify imports drastically
- Update the README file to more closely match our other repositories
- Dynamically generate editions when pushing textures rather than hardcoding java and bedrock
- Re-sort much of the bot — many submission-related functions have been moved to a nested "utility" folder, and the image-related functions have moved from /functions/textures/ to /functions/images. This change should be less felt thanks to the addition of the `module-aliases` npm module.

2023-09-01 07:46 UTC, TheRolfFR requested changes
Btw something we never used was the Axios instance https://axios-http.com/docs/instance. It would be super useful because you can type the base URL and login headers so you wouldn't have to type again

2023-09-01 07:46 UTC, TheRolfFR commented on functions/saveDB.js
> +	};
maybe set this in the arguments as  default value to be more flexible

2023-09-01 07:46 UTC, TheRolfFR commented on functions/saveDB.js
>  			if (DEBUG) console.error(err?.response?.data ?? err);
we should maybe return early (or at the end if you feel like it4s more appropriate) and propagate the error with something like:
```js
return Promise.reject(err);
```

2023-09-01 14:49 UTC, 3vorp commented on functions/saveDB.js
> +	};
good idea, will do

2023-09-02 08:08 UTC, TheRolfFR requested changes
We almost there

2023-09-02 08:08 UTC, TheRolfFR commented on functions/saveDB.js
> +			if (DEBUG) console.error(err?.response?.data ?? err);
Return early by rejecting a promise and the error inside

2023-09-02 08:08 UTC, TheRolfFR commented on functions/submission/downloadResults.js
> +		if (DEBUG) console.log(`Added contributions: ${allContribution}`);
We should make a list of all errors in this function and report them in a channel somewhere wether it's debug or not

2023-09-02 19:02 UTC, 3vorp commented on functions/saveDB.js
> +			if (DEBUG) console.error(err?.response?.data ?? err);
I don't want to return early because I still want to complete the backup even if a collection failed — there's a good chance the other collections succeeded anyways

2023-09-02 19:02 UTC, 3vorp commented on functions/saveDB.js
> +};
I'll see if moving it to settings would work better — I just copied the existing structure

2023-09-02 19:24 UTC, 3vorp commented on functions/saveDB.js
> +};
done with [cd4e7f3](https://github.com/Faithful-Resource-Pack/Discord-Bot/commit/cd4e7f34223d0707410ace71a1f97ce04865e895)

2023-09-02 19:25 UTC, 3vorp commented on functions/submission/downloadResults.js
> +		if (DEBUG) console.log(`Added contributions: ${allContribution}`);
honestly adding a general log/error function that unhandledRejection pulls from would be a good idea, since then this would be much more easy to implement

pretty sure the TS bot uses similar too

2023-09-02 19:59 UTC, 3vorp commented on functions/saveDB.js
> +			if (DEBUG) console.error(err?.response?.data ?? err);
decided to just log it using the new logger function I added

2023-09-02 21:49 UTC, merged